---
- hosts: all
  become: yes
  gather_facts: yes

  vars:
   - pkg_list: 
      - bc
      - perl
      - python3
      - libstdc++
   - disallowed_users:
      - bob
      - sue
      - mohammad

  tasks:
#    - name: DNS lookup of www.google.com
#      debug: 
#        msg: "Success!"
#      when: "{{ lookup('dig', 'www.google.com') }}"
  
  
    - name: Configrm Default Ueg Packages are installed
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ pkg_list }}"
  
    - name: Check if Netbackup (bpcd) process is running
      shell: >
        echo -n
        $(pgrep bpcd)
      check_mode: no
  
    - name: NTP
      service: 
        name: chronyd
        state: started

    - name: Confirm NTP config file is in place
      copy:
        src: chrony.conf
        dest: /etc/chrony.conf
        owner: root
        group: root
        mode: 0644
        setype: etc_t
  
    - name: Logrotation
      shell: /etc/cron.daily/logrotate
      register: logrotate_out
      ignore_errors: true
      check_mode: no

    - debug: msg="{{logrotate_out}}"

    - name: verify return code of logrotate command is 0 
      fail:
        msg: "Logrotate return code was not 0!"
      when: logrotate_out.rc != 0

    - name: Confirm autofs is working
      stat:
        path: /etc
      register: etc_out

    - name: Error if autofs is not working
      fail:
        msg: "Can't list contents of /etc!"
      when: etc_out.stat.isdir != true
      ignore_errors: true

    - name: Cron and At Disabled for non standard users in engineering Spec
      user:
        name: "{{ item }}"
        state: absent
      loop: "{{ disallowed_users }}"
    

